MVCEventManagement/MVCEventManagement/Controllers/FormController.cs
using MVCEventManagement.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEventManagement.Controllers
{
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Index()
        {
                 FormModel _model = new FormModel {
                _CreateEvent= new CreateEventModel { EventDate=DateTime.Now, EventID="Test", EventName="MyFirstEvent" },
                _CreatApplication= new CreateApplicationModel { ApplicationName="", EventID="", ApprovalNeeded=true, ExpirationDate=DateTime.Now.AddDays(90) },
                _MyEvents = new MyEventsModels { }
            };
            return View(_model);
        }
        
              
        public ActionResult MyEvents()
        {
            MyEventsModels model = new MyEventsModels();
            return PartialView("_MyEvents", model);
        }
       
        public ActionResult CreateNewEvent()
        {
            CreateEventModel model = new CreateEventModel();
            return PartialView("_CreateNewEvent", model);
        }
        public ActionResult EventDetails()
        {
            EventDetailsModel model = new EventDetailsModel();
            return PartialView("EventDetails", model);
        }
        [HttpGet]
        public ActionResult CreateApplication(string eventId)
        {
            CreateApplicationModel model = new CreateApplicationModel();
            model.inputs.Add("Yes");
            model.inputs.Add("No");
            model.EventID = eventId = "1";
            return PartialView("_CreateApplication", model);
        }

        [HttpPost]
        public ActionResult CreateApplication(CreateEventModel data)
        {
            CreateApplicationModel model = new CreateApplicationModel();
            model.EventID = data.EventID;
            List<string> items = new List<string> { "Yes", "No" };
            model.inputs = items;
            return PartialView("_CreateApplication",model);
        }       
        [HttpPost]
        public ActionResult ApplicationBuilder(CreateApplicationModel applicationdata)
        {
            return PartialView("ApplicationBuilder");
        }
        [HttpPost]
        public ActionResult Save(string inputs)
        {
            //check for null
            return View("Index");
        }

        public ActionResult Notification()
        {
            return PartialView("Notifications");
        }
        //public ActionResult MyEvents()
        //{

        //    List<MyEventsModels> DataList = new List<MyEventsModels>();
        //    DataList.Add(new MyEventsModels
        //    {
        //        EventName = "PDC_Application",
        //        IsActive = true,
        //        Submissions = 6,
        //        EventDetails = "Edit Details",
        //        CustomEmails = "Edit Emails",
        //        ApprovalsNeeded = true,
        //        EventDate = DateTime.Now               
        //    });
        //    DataList.Add(new MyEventsModels
        //    {
        //        EventName = "Webinar",
        //        IsActive = true,
        //        Submissions = 34,
        //        EventDetails = "Edit Details",
        //        CustomEmails = "Edit Emails",
        //        ApprovalsNeeded = true,
        //        EventDate = DateTime.Now
        //    });
        //    DataList.Add(new MyEventsModels
        //    {
        //        EventName = "RROC Application",
        //        IsActive = false,
        //        Submissions = 11,
        //        EventDetails = "Edit Details",
        //        CustomEmails = "Edit Emails",
        //        ApprovalsNeeded = false,
        //        EventDate = DateTime.Now
        //    });
        //    DataList.Add(new MyEventsModels
        //    {
        //        EventName = "MTC Pre-Survey",
        //        IsActive = false,
        //        Submissions = 21,
        //        EventDetails = "Edit Details",
        //        CustomEmails = "Edit Emails",
        //        ApprovalsNeeded = false,
        //        EventDate = DateTime.Now
        //    });

        //    DataList.Add(new MyEventsModels
        //    {
        //        EventName = "MTC Mentor Training",
        //        IsActive = true,
        //        Submissions = 6,
        //        EventDetails = "Edit Details",
        //        CustomEmails = "Edit Emails",
        //        ApprovalsNeeded = true,
        //        EventDate = DateTime.Now
        //    });
        //    return View(DataList);
        //}

        // GET: Form/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: Form/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Form/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Form/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Form/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Form/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Form/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

MVCEventManagement/MVCEventManagement/Views/Shared/_CreateEventSukul.cshtml
@model MVCEventManagement.Models.MyEventsModels
@{
    ViewBag.Title = "CreateEvent";
}
<h2>CreateEvent</h2>

@using (Html.BeginForm())
{
    <div id="createEvent ">
        @Html.RadioButton("Active", "true")Create a new Event
        <div>
            Title:@Html.TextBox("TITLE", "")<br>
            EventID:@Html.TextBox("Event", "")<br>
            DATE :@Html.EditorFor(item => item.EventDate)<br>
        </div>

    </div>
    <div id="Copy">
      @Html.RadioButton("Active", "false", "true") Create a new event by copying an old event <br>
        <p>
            Choose from the list of previous events @Html.DropDownList("Old Applications", new List<SelectListItem>()
              {
               new SelectListItem() { Text= "PDC_APPLICATION", Value = "PDC_Application" },
               new SelectListItem() { Text= "RROC_Application", Value = "rroc_application", Selected = true },
               new SelectListItem() { Text= "MTC presurvey", Value = "MTC_PRESURVEY", Selected = true }
               }, "Select ...")
            <br>
            Title:@Html.TextBox("TITLE1", "")<br>
            EventID:@Html.TextBox("EVENTID1", "")<br>
            DATE :@Html.EditorFor(item => item.EventDate)<br>
        </p>
    </div>
    <div id="continue">
        @Html.RadioButton("Active", "false", "true")Continue editing a created event
        <p>
            choose from the list of saved events @Html.DropDownList("Old Applications", new List<SelectListItem>()
             {
               new SelectListItem() { Text= "NEW_Event_name", Value = "PDC_Application" },
               new SelectListItem() { Text= "No saved events", Value = "rroc_application", Selected = true }
               }, "Select ...")
            <br>
        </p>
    </div>
    <p>
        @Html.ActionLink("Back", "Login")   @Html.ActionLink("Next", "CreateApplication")
    </p>
}

MVCEventManagement/MVCEventManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Formcss/demo.css" rel="stylesheet" />
    <link href="~/Content/Formcss/form-builder.css" rel="stylesheet" />
    <link href="~/Content/Formcss/form-render.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
            @*<div class="navbar-header">                
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>*@

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @using Microsoft.AspNet.Identity
                    @if (!Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Forms", "Index", "Form")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Form Builder Demo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ajax")
    @RenderSection("scripts", required: false)


   
</body>
</html>

MVCEventManagement/MVCEventManagement/Views/Shared/_Notifications.cshtml
@{
    ViewBag.Title = "Notifications";
}

<h2>Notifications</h2>
<h2>ADMINISTRATOR NOTIFICATIONS</h2>
<p>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Cancel &raquo;</a>
    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Save &raquo;</a>
    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Next &raquo;</a>
</p>
<h3>Select which notifications to turn on</h3>
@Html.Label("Receive an email when a user submits a registration application")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
@Html.Label("Receive an email when a user accepts an offer to join the event")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />

<h2>USER NOTIFICATIONS</h2>
@Html.Label("Send the user a confirmation email for submitting application")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
@Html.Label("Send the user an automated acceptance email")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
@Html.Label("Send the user an automated rejection email")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
@Html.Label("Send the user an automated recommendation email")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
@Html.Label("Send the user an automated  email with Event Details")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
@Html.Label("Send the user a reminder email to complete the application")&nbsp;
@Html.TextArea("Description", "Sample email text Placeholder", new { @class = "form-control" })
<br /><br />
<p>
    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Cancel &raquo;</a>
    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Save &raquo;</a>
    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Next &raquo;</a>
</p>